### ISSUE TITLE
Cannot load the project

### ISSUE THREAD

**Issue by rjramirez** [jsreport/jsreport-dotnet-example-consoleapp#1]
I tried opening it in various versions of Visual Studio but it doesn't load.
![capture123123](https://user-images.githubusercontent.com/2044483/34511116-5ab6fb8e-f094-11e7-8eea-7f04fd89785d.PNG)

![capturevs2010](https://user-images.githubusercontent.com/2044483/34511198-ad1f3b0c-f094-11e7-9625-9c02f11ba284.PNG)

**Comment by pofider** [comment]
I'm afraid you need to use 2017.
