### ISSUE TITLE
I cant Change invoiceReport content type

### ISSUE THREAD

**Issue by stormaref** [jsreport/jsreport-dotnet-example-consoleapp#2]
how can i change invoiceReport content type to image without saving pdf

**Comment by pofider** [comment]
You get back the binary stream from jsreport API and it is up to you what you do with it. 
If you intent to return the stream to the user from a web server, use the web server methods to add to the result stream header with proper contentType.

**Comment by stormaref** [comment]
@pofider when i want to use custom rendering  "Recipe = Recipe.PhantomImage" i get error that say cant find phantom-image

**Comment by pofider** [comment]
The `phantom-image` is a custom recipe extension which is not part of the standard binary packed in `jsreport.Binary`. Please see the docs section "Custom extensions" 
https://jsreport.net/learn/dotnet-local

**Comment by stormaref** [comment]
can u do an example with phantom-image? 
i reallllly need it and i cant add it in my app please share an example with console app and phantom-image 
thank you

**Comment by pofider** [comment]
What have you tried so far? Did you follow the instructions? 

Just make sure you install the 1.x version jsreport-phantom-image. So something like
npm i jsreport-phantom-image@1.0.2

**Comment by stormaref** [comment]
I tried to install it but it's not working
