### ISSUE TITLE
Generating this Report is taking to long

### ISSUE THREAD

**Issue by shahzaib142073** [jsreport/jsreport-dotnet-example-consoleapp#5]
when I generated this report it took quite a while for the report to be created which is causing a performance issue 

```
var rs = new LocalReporting()
                .RunInDirectory(Path.Combine(Directory.GetCurrentDirectory(), "jsreport"))
                .KillRunningJsReportProcesses()
                .UseBinary(JsReportBinary.GetBinary())
                .Configure(cfg => cfg.AllowedLocalFilesAccess().FileSystemStore().BaseUrlAsWorkingDirectory())
                .AsUtility()
                .Create();

            //Console.WriteLine("Rendering localy stored template jsreport/data/templates/Invoice into invoice.pdf");
            //var invoiceReport = rs.RenderByNameAsync("Invoice", InvoiceData).Result;
            //invoiceReport.Content.CopyTo(File.OpenWrite("invoice.pdf"));

            Console.WriteLine("Rendering custom report fully described through the request object into customReport.pdf");
            var customReport = rs.RenderAsync(CustomRenderRequest).Result;
            customReport.Content.CopyTo(File.OpenWrite("customReport.pdf"));
            Console.WriteLine("The application started at {0:HH:mm:ss.fff}", DateTime.Now);
            Console.ReadLine();
```

**Comment by pofider** [comment]
The second call to `rs.RenderAsync` should be much faster.
Can you verify it?

**Comment by shahzaib142073** [comment]
Yes it is generating it faster first report took about 30 sec while generating 20 report took 55 sec 
with time difference between generation being 2 sec

**Comment by pofider** [comment]
You get the 55sec rendering time with this example with the exact same templates? On your dev machine? That is very strange. It should be like 2sec.

Also, please try out the pre-release jsreport.Binary nuget. 
https://www.nuget.org/packages/jsreport.Binary/2.6.2-beta2

If your own templates and it is possible, please share a repo so I can take look.

**Comment by shahzaib142073** [comment]
PC SPECS:
Processor : Intel(R) Core(TM)i5-5200U CPU @2.20GHz 2.20Ghz
Ram : 8 GB

PROJECT DETAILS:
Target Framework : .NET Core 2.0 
packages version : Jsreport.Binary 2.4.0 , Jsreport.Binary 2.0.1

I am using the same repo, but this is the modified code.

```
using jsreport.Binary;
using jsreport.Local;
using jsreport.Types;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("The application started at {0:HH:mm:ss.fff}", DateTime.Now);

            var rs = new LocalReporting()
            .RunInDirectory(Path.Combine(Directory.GetCurrentDirectory(), "jsreport"))
            .KillRunningJsReportProcesses()
            .UseBinary(JsReportBinary.GetBinary())
            .Configure(cfg => cfg.AllowedLocalFilesAccess().FileSystemStore().BaseUrlAsWorkingDirectory())
            .AsUtility()
            .Create();

            Console.WriteLine("The application Initialized at {0:HH:mm:ss.fff}", DateTime.Now);



            




            

            Console.WriteLine("Rendering custom report fully described through the request object into customReport.pdf");
            for(int i=0;i<20;i++)
            {
                Stopwatch sw = Stopwatch.StartNew();
                var customReport = rs.RenderAsync(CustomRenderRequest).Result;
                customReport.Content.CopyTo(File.OpenWrite("D" + i.ToString() + "customReport.pdf"));
               
                sw.Stop();
                Console.WriteLine("Time taken: {0}ms", sw.Elapsed.TotalMilliseconds); 
            }
            
            Console.WriteLine("The application Ended at {0:HH:mm:ss.fff}", DateTime.Now);
            

          


            
            Console.ReadLine();
        }

        private static RenderRequest CustomRenderRequest = new RenderRequest()
        {
            Template = new Template()
            {
                Content = "Helo world from {{message}}",
                Engine = Engine.Handlebars,
                Recipe = Recipe.ChromePdf
            },
            Data = new
            {
                message = "jsreport for .NET!!!"
            }
        };

        static object InvoiceData = new
        {
            number = "123",
            seller = new
            {
                name = "Next Step Webs, Inc.",
                road = "12345 Sunny Road",
                country = "Sunnyville, TX 12345"
            },
            buyer = new
            {
                name = "Acme Corp.",
                road = "16 Johnson Road",
                country = "Paris, France 8060"
            },
            items = new[]
            {
                new { name = "Website design", price = 300 }
            }
        };
    }
}
```

RESULT:
The application started at 11:59:57.431
The application Initialized at 11:59:58.612
Rendering custom report fully described through the request object into customReport.pdf
Time taken: 27437.9264ms
Time taken: 3816.8042ms
Time taken: 3342.6664ms
Time taken: 3796.6234ms
Time taken: 3741.2207ms
Time taken: 4073.164ms
Time taken: 4305.8705ms
Time taken: 4316.6516ms
Time taken: 2457.1177ms
Time taken: 2357.4383ms
Time taken: 2479.2896ms
Time taken: 2390.6955ms
Time taken: 2601.1345ms
Time taken: 2512.3458ms
Time taken: 2623.1562ms
Time taken: 2324.2762ms
Time taken: 2302.2969ms
Time taken: 2434.7306ms
Time taken: 2324.279ms
Time taken: 2246.7132ms
The application Ended at 12:01:22.563

**Comment by pofider** [comment]
Ah ok. I didn't get what you mean. So you complain 2s rendering time for pdf.

You can update to the 2.6.2-beta2 pre-release. This should give you a 0.5-second improvement.
You can also create `jsreport.config.json`  file inside `jsreport` folder with this content.
```js
{
  "chrome": {
    "strategy":  "chrome-pool"
  }
}
```
This should get you to the 0.8s performance. See the [docs](https://jsreport.net/learn/chrome-pdf#reuse-chrome-instances).

You can also use `AsWebServer()` instead of `AsUtility`. This would be the fastest in the end.
https://jsreport.net/learn/dotnet-local#utility-or-web-server
